### ISSUE TITLE
Phospho_TMT Test data

### ISSUE THREAD

**Issue by kaupuks** [Nesvilab/FragPipeAnalystR#5]
I tried to repeat the phospho analysis from the data provided. (https://github.com/Nesvilab/FragPipeAnalystR/tree/main/tests/testthat/testdata/3plex_panRCC_TMT)

I got this warning.

> plot_pca(se, n=500, ID_col="label")
Warning messages:
1: Use of `pca_df[[indicate[1]]]` is discouraged.
ℹ Use `.data[[indicate[1]]]` instead. 
2: Use of `pca_df[[indicate[2]]]` is discouraged.
ℹ Use `.data[[indicate[2]]]` instead. 

Got an error.
> prepare_PTMSEA(de_result_updated, "Tumor_vs_NAT_diff", "./result.gct")
Error in `[.data.frame`(as.data.frame(rowData(se)), "SequenceWindow") : 
  undefined columns selected

> prepare_kinome(de_result_updated, "Tumor_vs_NAT_diff", "./result.gct")
Error in `[.data.frame`(as.data.frame(rowData(se)), "SequenceWindow") : 
  undefined columns selected

**Comment by hsiaoyi0504** [comment]
@kaupuks That's not a phospho data. Instead, it's a global proteome data.
